### ISSUE TITLE
Didn't find class "com.RNFetchBlob.Utils.FileProvider" on path: DexPathList

### ISSUE THREAD

**Issue by devgeeksclub** [joltup/rn-fetch-blob#446]
not able to compile android , I think cause I have enabled MultiDex because it working with another project with MultiDex disabled
"react-native": "0.59.10"
"rn-fetch-blob": "0.11.2",

any work around ?

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.telmeeth, PID: 21541
    java.lang.RuntimeException: Unable to get provider com.RNFetchBlob.Utils.FileProvider: java.lang.ClassNotFoundException: Didn't find class "com.RNFetchBlob.Utils.FileProvider" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.telmeeth-kN7eC712Z1vA50eVFsMe_w==/base.apk", zip file "/data/app/com.telmeeth-kN7eC712Z1vA50eVFsMe_w==/split_lib_dependencies_apk.apk", zip file "/data/app/com.telmeeth-kN7eC712Z1vA50eVFsMe_w==/split_lib_resources_apk.apk", zip file "/data/app/com.telmeeth-kN7eC712Z1vA50eVFsMe_w==/split_lib_slice_0_apk.apk", zip file "/data/app/com.telmeeth-kN7eC712Z1vA50eVFsMe_w==/split_lib_slice_1_apk.apk", zip file "/data/app/com.telmeeth-kN7eC712Z1vA50eVFsMe_w==/split_lib_slice_2_apk.apk", zip file "/data/app/com.telmeeth-kN7eC712Z1vA50eVFsMe_w==/split_lib_slice_3_apk.apk", zip file "/data/app/com.telmeeth-kN7eC712Z1vA50eVFsMe_w==/split_lib_slice_4_apk.apk", zip file "/data/app/com.telmeeth-kN7eC712Z1vA50eVFsMe_w==/split_lib_slice_5_apk.apk", zip file "/data/app/com.telmeeth-kN7eC712Z1vA50eVFsMe_w==/split_lib_slice_6_apk.apk", zip file "/data/app/com.telmeeth-kN7eC712Z1vA50eVFsMe_w==/split_lib_slice_7_apk.apk", zip file "/data/app/com.telmeeth-kN7eC712Z1vA50eVFsMe_w==/split_lib_slice_8_apk.apk", zip file "/data/app/com.telmeeth-kN7eC712Z1vA50eVFsMe_w==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.telmeeth-kN7eC712Z1vA50eVFsMe_w==/lib/x86, /data/app/com.telmeeth-kN7eC712Z1vA50eVFsMe_w==/base.apk!/lib/x86, /data/app/com.telmeeth-kN7eC712Z1vA50eVFsMe_w==/split_lib_dependencies_apk.apk!/lib/x86, /data/app/com.telmeeth-kN7eC712Z1vA50eVFsMe_w==/split_lib_resources_apk.apk!/lib/x86, /data/app/com.telmeeth-kN7eC712Z1vA50eVFsMe_w==/split_lib_slice_0_apk.apk!/lib/x86, /data/app/com.telmeeth-kN7eC712Z1vA50eVFsMe_w==/split_lib_slice_1_apk.apk!/lib/x86, /data/app/com.telmeeth-kN7eC712Z1vA50eVFsMe_w==/split_lib_slice_2_apk.apk!/lib/x86, /data/app/com.telmeeth-kN7eC712Z1vA50eVFsMe_w==/split_lib_slice_3_apk.apk!/lib/x86, /data/app/com.telmeeth-kN7eC712Z1vA50eVFsMe_w==/split_lib_slice_4_apk.apk!/lib/x86, /data/app/com.telmeeth-kN7eC712Z1vA50eVFsMe_w==/split_lib_slice_5_apk.apk!/lib/x86, /data/app/com.telmeeth-kN7eC712Z1vA50eVFsMe_w==/split_lib_slice_6_apk.apk!/lib/x86, /data/app/com.telmeeth-kN7eC712Z1vA50eVFsMe_w==/split_lib_slice_7_apk.apk!/lib/x86, /data/app/com.telmeeth-kN7eC712Z1vA50eVFsMe_w==/split_lib_slice_8_apk.apk!/lib/x86, /data/app/com.telmeeth-kN7eC712Z1vA50eVFsMe_w==/split_lib_slice_9_apk.apk!/lib/x86, /system/lib]]
        at android.app.ActivityThread.installProvider(ActivityThread.java:6396)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:5938)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5853)
        at android.app.ActivityThread.access$1100(ActivityThread.java:199)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
E/AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.RNFetchBlob.Utils.FileProvider" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.telmeeth-kN7eC712Z1vA50eVFsMe_w==/base.apk", zip file "/data/app/com.telmeeth-kN7eC712Z1vA50eVFsMe_w==/split_lib_dependencies_apk.apk", zip file "/data/app/com.telmeeth-kN7eC712Z1vA50eVFsMe_w==/split_lib_resources_apk.apk", zip file "/data/app/com.telmeeth-kN7eC712Z1vA50eVFsMe_w==/split_lib_slice_0_apk.apk", zip file "/data/app/com.telmeeth-kN7eC712Z1vA50eVFsMe_w==/split_lib_slice_1_apk.apk", zip file "/data/app/com.telmeeth-kN7eC712Z1vA50eVFsMe_w==/split_lib_slice_2_apk.apk", zip file "/data/app/com.telmeeth-kN7eC712Z1vA50eVFsMe_w==/split_lib_slice_3_apk.apk", zip file "/data/app/com.telmeeth-kN7eC712Z1vA50eVFsMe_w==/split_lib_slice_4_apk.apk", zip file "/data/app/com.telmeeth-kN7eC712Z1vA50eVFsMe_w==/split_lib_slice_5_apk.apk", zip file "/data/app/com.telmeeth-kN7eC712Z1vA50eVFsMe_w==/split_lib_slice_6_apk.apk", zip file "/data/app/com.telmeeth-kN7eC712Z1vA50eVFsMe_w==/split_lib_slice_7_apk.apk", zip file "/data/app/com.telmeeth-kN7eC712Z1vA50eVFsMe_w==/split_lib_slice_8_apk.apk", zip file "/data/app/com.telmeeth-kN7eC712Z1vA50eVFsMe_w==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.telmeeth-kN7eC712Z1vA50eVFsMe_w==/lib/x86, /data/app/com.telmeeth-kN7eC712Z1vA50eVFsMe_w==/base.apk!/lib/x86, /data/app/com.telmeeth-kN7eC712Z1vA50eVFsMe_w==/split_lib_dependencies_apk.apk!/lib/x86, /data/app/com.telmeeth-kN7eC712Z1vA50eVFsMe_w==/split_lib_resources_apk.apk!/lib/x86, /data/app/com.telmeeth-kN7eC712Z1vA50eVFsMe_w==/split_lib_slice_0_apk.apk!/lib/x86, /data/app/com.telmeeth-kN7eC712Z1vA50eVFsMe_w==/split_lib_slice_1_apk.apk!/lib/x86, /data/app/com.telmeeth-kN7eC712Z1vA50eVFsMe_w==/split_lib_slice_2_apk.apk!/lib/x86, /data/app/com.telmeeth-kN7eC712Z1vA50eVFsMe_w==/split_lib_slice_3_apk.apk!/lib/x86, /data/app/com.telmeeth-kN7eC712Z1vA50eVFsMe_w==/split_lib_slice_4_apk.apk!/lib/x86, /data/app/com.telmeeth-kN7eC712Z1vA50eVFsMe_w==/split_lib_slice_5_apk.apk!/lib/x86, /data/app/com.telmeeth-kN7eC712Z1vA50eVFsMe_w==/split_lib_slice_6_apk.apk!/lib/x86, /data/app/com.telmeeth-kN7eC712Z1vA50eVFsMe_w==/split_lib_slice_7_apk.apk!/lib/x86, /data/app/com.telmeeth-kN7eC712Z1vA50eVFsMe_w==/split_lib_slice_8_apk.apk!/lib/x86, /data/app/com.telmeeth-kN7eC712Z1vA50eVFsMe_w==/split_lib_slice_9_apk.apk!/lib/x86, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.AppComponentFactory.instantiateProvider(AppComponentFactory.java:121)
        at android.support.v4.app.CoreComponentFactory.instantiateProvider(CoreComponentFactory.java:62)
        at android.app.ActivityThread.installProvider(ActivityThread.java:6380)
        	... 10 more
    	Suppressed: java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/core/content/FileProvider;
        at java.lang.VMClassLoader.findLoadedClass(Native Method)
        at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
        		... 14 more
E/AndroidRuntime: 	Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.core.content.FileProvider" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.telmeeth-kN7eC712Z1vA50eVFsMe_w==/base.apk", zip file "/data/app/com.telmeeth-kN7eC712Z1vA50eVFsMe_w==/split_lib_dependencies_apk.apk", zip file "/data/app/com.telmeeth-kN7eC712Z1vA50eVFsMe_w==/split_lib_resources_apk.apk", zip file "/data/app/com.telmeeth-kN7eC712Z1vA50eVFsMe_w==/split_lib_slice_0_apk.apk", zip file "/data/app/com.telmeeth-kN7eC712Z1vA50eVFsMe_w==/split_lib_slice_1_apk.apk", zip file "/data/app/com.telmeeth-kN7eC712Z1vA50eVFsMe_w==/split_lib_slice_2_apk.apk", zip file "/data/app/com.telmeeth-kN7eC712Z1vA50eVFsMe_w==/split_lib_slice_3_apk.apk", zip file "/data/app/com.telmeeth-kN7eC712Z1vA50eVFsMe_w==/split_lib_slice_4_apk.apk", zip file "/data/app/com.telmeeth-kN7eC712Z1vA50eVFsMe_w==/split_lib_slice_5_apk.apk", zip file "/data/app/com.telmeeth-kN7eC712Z1vA50eVFsMe_w==/split_lib_slice_6_apk.apk", zip file "/data/app/com.telmeeth-kN7eC712Z1vA50eVFsMe_w==/split_lib_slice_7_apk.apk", zip file "/data/app/com.telmeeth-kN7eC712Z1vA50eVFsMe_w==/split_lib_slice_8_apk.apk", zip file "/data/app/com.telmeeth-kN7eC712Z1vA50eVFsMe_w==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.telmeeth-kN7eC712Z1vA50eVFsMe_w==/lib/x86, /data/app/com.telmeeth-kN7eC712Z1vA50eVFsMe_w==/base.apk!/lib/x86, /data/app/com.telmeeth-kN7eC712Z1vA50eVFsMe_w==/split_lib_dependencies_apk.apk!/lib/x86, /data/app/com.telmeeth-kN7eC712Z1vA50eVFsMe_w==/split_lib_resources_apk.apk!/lib/x86, /data/app/com.telmeeth-kN7eC712Z1vA50eVFsMe_w==/split_lib_slice_0_apk.apk!/lib/x86, /data/app/com.telmeeth-kN7eC712Z1vA50eVFsMe_w==/split_lib_slice_1_apk.apk!/lib/x86, /data/app/com.telmeeth-kN7eC712Z1vA50eVFsMe_w==/split_lib_slice_2_apk.apk!/lib/x86, /data/app/com.telmeeth-kN7eC712Z1vA50eVFsMe_w==/split_lib_slice_3_apk.apk!/lib/x86, /data/app/com.telmeeth-kN7eC712Z1vA50eVFsMe_w==/split_lib_slice_4_apk.apk!/lib/x86, /data/app/com.telmeeth-kN7eC712Z1vA50eVFsMe_w==/split_lib_slice_5_apk.apk!/lib/x86, /data/app/com.telmeeth-kN7eC712Z1vA50eVFsMe_w==/split_lib_slice_6_apk.apk!/lib/x86, /data/app/com.telmeeth-kN7eC712Z1vA50eVFsMe_w==/split_lib_slice_7_apk.apk!/lib/x86, /data/app/com.telmeeth-kN7eC712Z1vA50eVFsMe_w==/split_lib_slice_8_apk.apk!/lib/x86, /data/app/com.telmeeth-kN7eC712Z1vA50eVFsMe_w==/split_lib_slice_9_apk.apk!/lib/x86, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        		... 17 more
    		Suppressed: java.io.IOException: No original dex files found for dex location /data/app/com.telmeeth-kN7eC712Z1vA50eVFsMe_w==/split_lib_resources_apk.apk
        at dalvik.system.DexFile.openDexFileNative(Native Method)
        at dalvik.system.DexFile.openDexFile(DexFile.java:354)
        at dalvik.system.DexFile.<init>(DexFile.java:101)
        at dalvik.system.DexFile.<init>(DexFile.java:75)
        at dalvik.system.DexPathList.loadDexFile(DexPathList.java:394)
        at dalvik.system.DexPathList.makeDexElements(DexPathList.java:354)
        at dalvik.system.DexPathList.<init>(DexPathList.java:164)
        at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:74)
        at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:65)
        at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:64)
        at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:73)
        at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:88)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:74)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:40)
        at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:727)
        at android.app.LoadedApk.getClassLoader(LoadedApk.java:810)
        at android.app.LoadedApk.getResources(LoadedApk.java:1032)
        at android.app.ContextImpl.createAppContext(ContextImpl.java:2345)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5749)
        			... 8 more
    	[CIRCULAR REFERENCE:java.io.IOException: No original dex files found for dex location /data/app/com.telmeeth-kN7eC712Z1vA50eVFsMe_w==/split_lib_resources_apk.apk]
```

**Comment by maneeshprajapati** [comment]
Hi I am also facing same issue. Did you get any update on this?

**Comment by evan0708** [comment]
Hi I am also facing same issue. Wondering if any update??

**Comment by KarenQiao** [comment]
same issue,any update?

**Comment by saidhappy010** [comment]
Hi.
Someone has found the solution?.
Thanks.

**Comment by toby-lei** [comment]
same issue

**Comment by RonRadtke** [comment]
I was facing the same problem.
Found a note on the github repo:

> Version Compatibility Warning
rn-fetch-blob version 0.10.16 is only compatible with react native 0.60 and up. It should have been a major version bump, we apologize for the mistake. If you are not yet upgraded to react native 0.60 or above, you should remain on rn-fetch-blob version 0.10.15

So I decided to downgrade from 0.12.x to 0.10.15 and it worked.
