### ISSUE TITLE
Android 8,9,10 - issue on emulator with getRealPathFromURI - NumberFormatException

### ISSUE THREAD

**Issue by Yurrili** [joltup/rn-fetch-blob#498]
Hi, I have issue with get image from downloads file on emulator.
My path: content://com.android.providers.downloads.documents/document/msf%3A253

And I've got this error:
` java.lang.NumberFormatException: For input string: "msf:253"
        at java.lang.Long.parseLong(Long.java:594)
        at java.lang.Long.valueOf(Long.java:808)
        at com.RNFetchBlob.Utils.PathResolver.getRealPathFromURI(PathResolver.java:47)`

Is it connected to testing on emulator?

 **I am using:**
> **Android:**
>         buildToolsVersion = "28.0.3"
>         minSdkVersion = 16
>         compileSdkVersion = 28
>         targetSdkVersion = 28
>         supportLibVersion = "28.0.0"
> **RN:**
>        "react": "16.9.0",
>        "react-native": "0.61.4",

**Comment by sentry0** [comment]
I had this problem and resolved it by stripping of the "content://" part of the uri.  You should also do this for "file://" prefixes as well.

```
let filePath = filePath.indexOf('//' >= -1) ? uri.split('//')[1] : uri;
```

**Comment by ThadeusAjayi** [comment]
Am having this same issue, I use a real device: Google Pixel 2xl running android 10

**Comment by aprilmintacpineda** [comment]
I'm having the same trouble with this path, android seems to sometimes return a path like: `content://com.android.providers.downloads.documents/document/893` or like `content://com.android.providers.downloads.documents/document/raw%3A%2Fstorage%2Femulated%2F0%2FDownload%2Fapplication_form.pdf`, notice the difference is with the file path. When I do:

```js
fs.stat('content://com.android.providers.downloads.documents/document/raw%3A%2Fstorage%2Femulated%2F0%2FDownload%2Fapplication_form.pdf');
```

it succeeds but when I do:

```js
fs.stat('content://com.android.providers.downloads.documents/document/893');
```

even though both of which was returned by [expo-document-picker](https://github.com/expo/expo)

- [Related issue](https://github.com/expo/expo/issues/263)
