### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'DocumentDir')

### ISSUE THREAD

**Issue by MohammedTAgha** [joltup/rn-fetch-blob#765]
I have just installed this library but when I am importing it into my project I have an error 
**

TypeError: Cannot read properties of undefined (reading 'DocumentDir')
at node_modules\expo\build\logs\LogSerialization.js:156:14 in _captureConsoleStackTrace
at node_modules\expo\build\logs\LogSerialization.js:41:26 in serializeLogDataAsync
- ... 9 more stack frames from framework internals

**Comment by Francesco-Voto** [comment]
As workaround for the moment we can try something like 

```
jest.mock('rn-fetch-blob', () => ({
  fs: {
    dirs: {
      CacheDir: './',
    },
    unlink: jest.fn(),
  },
  config: () => ({
    fetch: jest.fn(),
  }),
}));
```
